// <auto-generated />
using Clima.Data;
using Clima.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore;
using MudBlazor;

namespace Clima.Components.Pages
{
    public partial class Dash
    {
        private Tb_registos latestReading;
        private List<Tb_registos> historicalData;
        private List<Tb_registos> recentRecords;
        private List<ChartSeries> historicalSeries = new();
        private string[] historicalLabels = Array.Empty<string>();
        [Inject] AppDbContext DbContext { get; set; }

        private PeriodType currentPeriod = PeriodType.Hour;
        private ChartOptions chartOptions = new ChartOptions
        {
            InterpolationOption = InterpolationOption.Straight,
            YAxisFormat = "0.##",
            YAxisTicks = 5,
            ChartPalette = new string[] { "#e74c3c", "#3498db", "#f39c12" }
        };

        private enum PeriodType
        {
            Hour,
            Day,
            Week
        }

        private double[] GetRiskFactorsData(Tb_registos reading)
        {
            // Keep risk levels in their original 1-3 scale
            double tempRisk = reading.risco_temperatura;
            double humidityRisk = reading.risco_humidade;

            // Convert radiation to a 1-3 scale
            double radiationMax = 1023.0; // Maximum possible radiation value
            double radiationNormalized = reading.radiacao / radiationMax;
            double radiationRisk = 1 + (radiationNormalized * 2); // Maps 0-1 to 1-3

            return new double[] { tempRisk, humidityRisk, radiationRisk };
        }

        private void ChangeHistoryPeriod(PeriodType period)
        {
            currentPeriod = period;
            SetupHistoricalChart();
            StateHasChanged();
        }

        private string GetHistoryTimeRangeText()
        {
            return currentPeriod switch
            {
                PeriodType.Hour => "Última hora de monitorização",
                PeriodType.Day => "Últimas 24 horas de monitorização",
                PeriodType.Week => "Últimos 7 dias de monitorização",
                _ => "Monitorização"
            };
        }

        protected override async Task OnInitializedAsync()
        {
            await LoadData();
            // Set up a timer to refresh data every minute
            var timer = new System.Threading.Timer(async _ =>
            {
                await LoadData();
                await InvokeAsync(StateHasChanged);
            }, null, TimeSpan.Zero, TimeSpan.FromMinutes(1));
        }
        private int CalculateRadiationRisk(double radiation)
        {
            // Define thresholds for radiation risk levels
            // Assuming average radiation is 500, we'll set thresholds accordingly
            if (radiation < 300) return 1; // Low risk
            else if (radiation < 700) return 2; // Medium risk
            else return 3; // High risk
        }

        private async Task LoadData()
        {
            try
            {
                // Replace with your actual API endpoints
                historicalData = await DbContext.Tb_Registos.ToListAsync();
                recentRecords = historicalData.OrderByDescending(o => o.data_registo).Take(10).ToList();

                if (historicalData != null && historicalData.Any())
                {
                    // Get the latest reading
                    latestReading = historicalData.OrderByDescending(x => x.data_registo).FirstOrDefault();

                    // Prepare chart data
                    SetupHistoricalChart();
                }
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading data: {ex.Message}");
                // You could show an error message here with MudBlazor components
            }
        }

        private void SetupHistoricalChart()
        {
            if (historicalData == null || !historicalData.Any())
                return;

            // Ordenar os dados por data/hora
            var orderedData = historicalData.OrderBy(x => x.data_registo).ToList();

            // Filtrar dados com base no período selecionado
            var filteredData = currentPeriod switch
            {
                PeriodType.Hour => orderedData.Where(x => x.data_registo >= DateTime.Now.AddHours(-1)).ToList(),
                PeriodType.Day => orderedData.Where(x => x.data_registo >= DateTime.Now.AddDays(-1)).ToList(),
                PeriodType.Week => orderedData.Where(x => x.data_registo >= DateTime.Now.AddDays(-7)).ToList(),
                _ => orderedData.Where(x => x.data_registo >= DateTime.Now.AddHours(-1)).ToList()
            };

            // Se não houver dados suficientes, use os últimos registros disponíveis
            if (!filteredData.Any())
            {
                filteredData = orderedData.TakeLast(Math.Min(orderedData.Count, 20)).ToList();
            }

            // Definir o número de pontos a mostrar no gráfico
            int pointsToShow = currentPeriod switch
            {
                PeriodType.Hour => 12,  // One point every 5 minutes
                PeriodType.Day => 12,   // One point every 2 hours (reduced from 24)
                PeriodType.Week => 14,  // Two points per day (reduced from 21)
                _ => 12
            };

            // Agrupar dados para reduzir a quantidade de pontos no gráfico
            var groupedData = GroupDataByPeriod(filteredData, pointsToShow);

            // Preparar rótulos para o eixo X
            historicalLabels = groupedData.Select(g => FormatDateLabel(g.Key, currentPeriod)).ToArray();

            // Preparar séries de dados
            var riskValues = groupedData.Select(g => g.Average(x => x.risco_incendio * 100)).ToArray();
            var tempValues = groupedData.Select(g => g.Average(x => x.temperatura)).ToArray();
            var humidityValues = groupedData.Select(g => g.Average(x => x.humidade)).ToArray();

            historicalSeries = new List<ChartSeries>
        {
            new ChartSeries { Name = "Risco de Incêndio (%)", Data = riskValues },
            new ChartSeries { Name = "Temperatura (°C)", Data = tempValues },
            new ChartSeries { Name = "Humidade (%)", Data = humidityValues }
        };
        }

        private IEnumerable<IGrouping<DateTime, Tb_registos>> GroupDataByPeriod(List<Tb_registos> data, int targetPoints)
        {
            if (data.Count <= targetPoints)
            {
                // Se temos menos pontos que o desejado, use cada ponto individualmente
                return data.GroupBy(x => x.data_registo);
            }

            // Determine o intervalo de tempo total
            var startTime = data.Min(x => x.data_registo);
            var endTime = data.Max(x => x.data_registo);
            var totalTimeSpan = endTime - startTime;

            // Calcule o intervalo para cada grupo
            var intervalPerGroup = TimeSpan.FromTicks(totalTimeSpan.Ticks / targetPoints);

            // Agrupe os dados por intervalo
            return data.GroupBy(x => RoundToInterval(x.data_registo, startTime, intervalPerGroup));
        }



        private DateTime RoundToInterval(DateTime date, DateTime startTime, TimeSpan interval)
        {
            var ticksFromStart = date.Ticks - startTime.Ticks;
            var intervals = (long)(ticksFromStart / interval.Ticks);
            return new DateTime(startTime.Ticks + intervals * interval.Ticks);
        }

        private string FormatDateLabel(DateTime date, PeriodType period)
        {
            return period switch
            {
                PeriodType.Hour => date.ToString("HH:mm"),
                PeriodType.Day => date.ToString("HH") + "h", // Just show the hour with 'h' suffix
                PeriodType.Week => date.ToString("dd/MM"), // Keep as is or could use "d/M" for even more compact
                _ => date.ToString("HH:mm")
            };
        }

        private double GetRiskPercentage(double riskValue)
        {
            // Convert risk values to percentage (0-100)
            return riskValue * 100;
        }

        private Color GetRiskColor(double riskValue)
        {
            if (riskValue < 11) return Color.Success;
            else if (riskValue < 31) return Color.Info;
            else if (riskValue < 51) return Color.Warning;
            else if (riskValue < 71) return Color.Error;
            else return Color.Dark;
        }
        private Color GetRiskColor2(double riskValue)
        {
            if (riskValue == 1) return Color.Info;
            else if (riskValue == 2) return Color.Warning;
            else return Color.Error;
        }

        private string GetRiskBackgroundClass(double riskValue)
        {
            double percentage = riskValue * 100;
            if (percentage < 11) return "risk-very-low";
            else if (percentage < 31) return "risk-low";
            else if (percentage < 51) return "risk-moderate";
            else if (percentage < 71) return "risk-high";
            else return "risk-very-high";
        }

        private string GetRiskLevel(double riskValue)
        {
            if (riskValue * 100 < 11) return "Muito Baixo";
            else if (riskValue * 100 < 31) return "Baixo";
            else if (riskValue * 100 < 51) return "Moderado";
            else if (riskValue * 100 < 71) return "Alto";
            else return "Muito Alto";
        }

        private Severity GetAlertSeverity(double riskValue)
        {
            if (riskValue * 100 < 11) return Severity.Success;
            else if (riskValue * 100 < 31) return Severity.Info;
            else if (riskValue * 100 < 51) return Severity.Warning;
            else if (riskValue * 100 < 71) return Severity.Error;
            else return Severity.Error;
        }

        private string GetAlertIcon(double riskValue)
        {
            if (riskValue * 100 < 11) return Icons.Material.Filled.CheckCircle;
            else if (riskValue * 100 < 31) return Icons.Material.Filled.Info;
            else if (riskValue * 100 < 51) return Icons.Material.Filled.Warning;
            else if (riskValue * 100 < 71) return Icons.Material.Filled.Error;
            else return Icons.Material.Filled.PriorityHigh;
        }

        private string GetAlertMessage(double riskValue)
        {
            if (riskValue * 100 < 11) return "Estado Normal - Sem alertas ativos";
            else if (riskValue * 100 < 31) return "Atenção - Monitoramento regular recomendado";
            else if (riskValue * 100 < 51) return "Alerta - Vigilância aumentada necessária";
            else if (riskValue * 100 < 71) return "Perigo - Alto risco de incêndio";
            else return "EMERGÊNCIA - Risco extremo de incêndio";
        }

        private string GetRiskRecommendation(double riskValue)
        {
            if (riskValue * 100 < 11) return "Condições favoráveis. Manter monitorização regular.";
            else if (riskValue * 100 < 31) return "Manter vigilância. Verificar sensores regularmente.";
            else if (riskValue * 100 < 51) return "Aumentar frequência de monitorização. Preparar recursos preventivos.";
            else if (riskValue * 100 < 71) return "Ativar protocolos de prevenção. Alertar equipes de resposta.";
            else return "Implementar medidas de emergência imediatamente. Acionar todos os recursos disponíveis.";
        }

        private string GetActionButton(double riskValue)
        {
            if (riskValue * 100 < 11) return "Relatório de Condições";
            else if (riskValue * 100 < 31) return "Verificar Sensores";
            else if (riskValue * 100 < 51) return "Ativar Monitoramento";
            else if (riskValue * 100 < 71) return "Iniciar Prevenção";
            else return "ACIONAR EMERGÊNCIA";
        }
    }
}